#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MazBrokes.Resource", IsApplication=true)]

namespace MazBrokes
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideDown = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideLeft = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SlideRight = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slideup = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int darkblue = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int grey = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int lightblue = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_overflow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int nicubunu_Soccer_ball = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ProgressBarStyle = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090014
			public const int Frag3List = 2131296276;
			
			// aapt resource value: 0x7f09001e
			public const int OutcomeRow = 2131296286;
			
			// aapt resource value: 0x7f09000e
			public const int btnDialogEmail = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int btnDialogSignIn = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int btnPlaceBet = 2131296265;
			
			// aapt resource value: 0x7f090018
			public const int btnSignIn = 2131296280;
			
			// aapt resource value: 0x7f09001a
			public const int btnSignUp = 2131296282;
			
			// aapt resource value: 0x7f09001f
			public const int item_subtitle = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int item_title = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int listEvents = 2131296289;
			
			// aapt resource value: 0x7f090005
			public const int lstBetList = 2131296261;
			
			// aapt resource value: 0x7f090012
			public const int lstBetOptions = 2131296274;
			
			// aapt resource value: 0x7f090022
			public const int menu = 2131296290;
			
			// aapt resource value: 0x7f09001b
			public const int progressBar1 = 2131296283;
			
			// aapt resource value: 0x7f090000
			public const int relLayBetList = 2131296256;
			
			// aapt resource value: 0x7f090011
			public const int relativeLayout1 = 2131296273;
			
			// aapt resource value: 0x7f09001d
			public const int sample_content_fragment = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int sample_main_layout = 2131296284;
			
			// aapt resource value: 0x7f090015
			public const int sliding_tabs = 2131296277;
			
			// aapt resource value: 0x7f090004
			public const int textView1 = 2131296260;
			
			// aapt resource value: 0x7f090008
			public const int txtBetAmount = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int txtBetListAmount = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int txtBetListOdds = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int txtBetListTitle = 2131296257;
			
			// aapt resource value: 0x7f090017
			public const int txtCreateAccount = 2131296279;
			
			// aapt resource value: 0x7f09000a
			public const int txtEmail = 2131296266;
			
			// aapt resource value: 0x7f090013
			public const int txtEvent = 2131296275;
			
			// aapt resource value: 0x7f090010
			public const int txtEventDesc = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int txtEventName = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int txtFirstName = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int txtOutcomeDetails = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int txtPassword = 2131296267;
			
			// aapt resource value: 0x7f090019
			public const int txtSignOr = 2131296281;
			
			// aapt resource value: 0x7f090006
			public const int txtWallet = 2131296262;
			
			// aapt resource value: 0x7f090016
			public const int viewpager = 2131296278;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BetListRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Chat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DashBoardLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_Bet = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_sign_in = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_sign_up = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int event_description = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EventPage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EventRow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Frag3Layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_sample = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int OutcomeListRow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int pager_item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int UpcomingEvents = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar_main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
